### ISSUE TITLE
Update for MobileMiner API Changes

### ISSUE THREAD

**Issue by nwoolls** [Axadiw/CGMinerMobileAdapter#1]
This also went out via email:

This email serves as a final warning about two important changes to the MobileMiner Statistics API. Support for & adherence to these changes is now required. Original emails went out on March 4th.
- The MinerName property on the JSON object is now required. This has been requested in the documentation for a long time but some folks still are not supplying a miner name.
- Your miner / script should be sending a single HTTP POST for all machines on the network. This will help alleviate network congestion and server load.

The first requirement is very straight forward: as long as you are specifying a name for your miner software or script in the MinerName property on you are all set.

For the second requirement I have documented the changes here:

http://mobileminerapp.com#api

You should no longer send the MachineName as an argument in the URL query string. Instead you should provide the MachineName on the JSON object you are sending via HTTP POST.

In addition, if your script or miner reports on multiple machines on the same network, it should do this using a single HTTP POST using the above format.

Effective immediately, requests that do not specify a MinerName will result in an HTTP error. In addition, requests to the statistics URL passing the MachineName in the query string will also result in an HTTP error.

Finally, effective immediately I will also be adjusting the throttling to ensure that any "farms" are reporting statistics using a single HTTP POST rather than one call for every machine.

I believe these adjustments will help the MobileMiner API grow and remain responsive as we continue to take on new users.

Please let me know if you have any questions at all and thanks again for being a MobileMiner API developer!

**Comment by Axadiw** [comment]
Fixed: https://github.com/Axadiw/CGMinerMobileAdapter/pull/2
